; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino


lib_deps =
    mathertel/OneButton @ ^2.6.1

monitor_speed = 115200
upload_speed = 921600

build_flags =
    '-D LED1_PIN=4U'
    '-D LED1_ACT=HIGH'
    '-D LED2_PIN=2U'
    '-D LED2_ACT=HIGH'
    '-D BTN1_PIN=0U'
    '-D BTN1_ACT=LOW'
    '-D BTN2_PIN=1U'
    '-D BTN2_ACT=LOW'
    

